version: "3"
services:
  postgres:
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs12"
    ports:
      - "5434:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs12:size=4g
